cyclic_diff_drive_command_publisher:
  ros__parameters:
    goal_names: ["pos1", "pos2", "pos3", "pos4", "stop"]
    pos1: [0.5, 0.5]
    pos2: [-0.3, 0.0]
    pos3: [0.9, 0.7]
    pos4: [0.3, 0.0]
    stop: [0.0, 0.0]